#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Zero
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Электронный_журнал")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    partial void InsertПользователь(Пользователь instance);
    partial void UpdateПользователь(Пользователь instance);
    partial void DeleteПользователь(Пользователь instance);
    partial void InsertОценка(Оценка instance);
    partial void UpdateОценка(Оценка instance);
    partial void DeleteОценка(Оценка instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Project_Zero.Properties.Settings.Default.Электронный_журналConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Пользователь> Пользователь
		{
			get
			{
				return this.GetTable<Пользователь>();
			}
		}
		
		public System.Data.Linq.Table<Оценка> Оценка
		{
			get
			{
				return this.GetTable<Оценка>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Пользователь")]
	public partial class Пользователь : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_пользователя;
		
		private string _ФИО;
		
		private string _Группа;
		
		private string _Электронный_адрес;
		
		private string _Логин;
		
		private string _Дата_рождения;
		
		private string _Статус;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_пользователяChanging(int value);
    partial void OnID_пользователяChanged();
    partial void OnФИОChanging(string value);
    partial void OnФИОChanged();
    partial void OnГруппаChanging(string value);
    partial void OnГруппаChanged();
    partial void OnЭлектронный_адресChanging(string value);
    partial void OnЭлектронный_адресChanged();
    partial void OnЛогинChanging(string value);
    partial void OnЛогинChanged();
    partial void OnДата_рожденияChanging(string value);
    partial void OnДата_рожденияChanged();
    partial void OnСтатусChanging(string value);
    partial void OnСтатусChanged();
    #endregion
		
		public Пользователь()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_пользователя", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_пользователя
		{
			get
			{
				return this._ID_пользователя;
			}
			set
			{
				if ((this._ID_пользователя != value))
				{
					this.OnID_пользователяChanging(value);
					this.SendPropertyChanging();
					this._ID_пользователя = value;
					this.SendPropertyChanged("ID_пользователя");
					this.OnID_пользователяChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ФИО", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string ФИО
		{
			get
			{
				return this._ФИО;
			}
			set
			{
				if ((this._ФИО != value))
				{
					this.OnФИОChanging(value);
					this.SendPropertyChanging();
					this._ФИО = value;
					this.SendPropertyChanged("ФИО");
					this.OnФИОChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Группа", DbType="NVarChar(5)")]
		public string Группа
		{
			get
			{
				return this._Группа;
			}
			set
			{
				if ((this._Группа != value))
				{
					this.OnГруппаChanging(value);
					this.SendPropertyChanging();
					this._Группа = value;
					this.SendPropertyChanged("Группа");
					this.OnГруппаChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Электронный_адрес", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string Электронный_адрес
		{
			get
			{
				return this._Электронный_адрес;
			}
			set
			{
				if ((this._Электронный_адрес != value))
				{
					this.OnЭлектронный_адресChanging(value);
					this.SendPropertyChanging();
					this._Электронный_адрес = value;
					this.SendPropertyChanged("Электронный_адрес");
					this.OnЭлектронный_адресChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Логин", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Логин
		{
			get
			{
				return this._Логин;
			}
			set
			{
				if ((this._Логин != value))
				{
					this.OnЛогинChanging(value);
					this.SendPropertyChanging();
					this._Логин = value;
					this.SendPropertyChanged("Логин");
					this.OnЛогинChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Дата_рождения", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Дата_рождения
		{
			get
			{
				return this._Дата_рождения;
			}
			set
			{
				if ((this._Дата_рождения != value))
				{
					this.OnДата_рожденияChanging(value);
					this.SendPropertyChanging();
					this._Дата_рождения = value;
					this.SendPropertyChanged("Дата_рождения");
					this.OnДата_рожденияChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Статус", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Статус
		{
			get
			{
				return this._Статус;
			}
			set
			{
				if ((this._Статус != value))
				{
					this.OnСтатусChanging(value);
					this.SendPropertyChanging();
					this._Статус = value;
					this.SendPropertyChanged("Статус");
					this.OnСтатусChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Оценка")]
	public partial class Оценка : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_оценки;
		
		private System.DateTime _Дата_оценки;
		
		private System.Nullable<int> _БДиСУБД;
		
		private System.Nullable<int> _КПиЯП;
		
		private System.Nullable<int> _Комьютерные_сети;
		
		private System.Nullable<int> _ПРСПО;
		
		private System.Nullable<int> _АУДО;
		
		private System.Nullable<int> _ПССIП;
		
		private System.Nullable<int> _ТиОПО;
		
		private System.Nullable<int> _ФКиЗ;
		
		private System.Nullable<int> _Матмод;
		
		private System.Nullable<int> _ЗКИ;
		
		private System.Nullable<int> _ТРПО;
		
		private System.Nullable<int> _ОП;
		
		private int _ID_пользователя;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_оценкиChanging(int value);
    partial void OnID_оценкиChanged();
    partial void OnДата_оценкиChanging(System.DateTime value);
    partial void OnДата_оценкиChanged();
    partial void OnБДиСУБДChanging(System.Nullable<int> value);
    partial void OnБДиСУБДChanged();
    partial void OnКПиЯПChanging(System.Nullable<int> value);
    partial void OnКПиЯПChanged();
    partial void OnКомьютерные_сетиChanging(System.Nullable<int> value);
    partial void OnКомьютерные_сетиChanged();
    partial void OnПРСПОChanging(System.Nullable<int> value);
    partial void OnПРСПОChanged();
    partial void OnАУДОChanging(System.Nullable<int> value);
    partial void OnАУДОChanged();
    partial void OnПССIПChanging(System.Nullable<int> value);
    partial void OnПССIПChanged();
    partial void OnТиОПОChanging(System.Nullable<int> value);
    partial void OnТиОПОChanged();
    partial void OnФКиЗChanging(System.Nullable<int> value);
    partial void OnФКиЗChanged();
    partial void OnМатмодChanging(System.Nullable<int> value);
    partial void OnМатмодChanged();
    partial void OnЗКИChanging(System.Nullable<int> value);
    partial void OnЗКИChanged();
    partial void OnТРПОChanging(System.Nullable<int> value);
    partial void OnТРПОChanged();
    partial void OnОПChanging(System.Nullable<int> value);
    partial void OnОПChanged();
    partial void OnID_пользователяChanging(int value);
    partial void OnID_пользователяChanged();
    #endregion
		
		public Оценка()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_оценки", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_оценки
		{
			get
			{
				return this._ID_оценки;
			}
			set
			{
				if ((this._ID_оценки != value))
				{
					this.OnID_оценкиChanging(value);
					this.SendPropertyChanging();
					this._ID_оценки = value;
					this.SendPropertyChanged("ID_оценки");
					this.OnID_оценкиChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Дата_оценки", DbType="Date NOT NULL")]
		public System.DateTime Дата_оценки
		{
			get
			{
				return this._Дата_оценки;
			}
			set
			{
				if ((this._Дата_оценки != value))
				{
					this.OnДата_оценкиChanging(value);
					this.SendPropertyChanging();
					this._Дата_оценки = value;
					this.SendPropertyChanged("Дата_оценки");
					this.OnДата_оценкиChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_БДиСУБД", DbType="Int")]
		public System.Nullable<int> БДиСУБД
		{
			get
			{
				return this._БДиСУБД;
			}
			set
			{
				if ((this._БДиСУБД != value))
				{
					this.OnБДиСУБДChanging(value);
					this.SendPropertyChanging();
					this._БДиСУБД = value;
					this.SendPropertyChanged("БДиСУБД");
					this.OnБДиСУБДChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_КПиЯП", DbType="Int")]
		public System.Nullable<int> КПиЯП
		{
			get
			{
				return this._КПиЯП;
			}
			set
			{
				if ((this._КПиЯП != value))
				{
					this.OnКПиЯПChanging(value);
					this.SendPropertyChanging();
					this._КПиЯП = value;
					this.SendPropertyChanged("КПиЯП");
					this.OnКПиЯПChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Комьютерные_сети", DbType="Int")]
		public System.Nullable<int> Комьютерные_сети
		{
			get
			{
				return this._Комьютерные_сети;
			}
			set
			{
				if ((this._Комьютерные_сети != value))
				{
					this.OnКомьютерные_сетиChanging(value);
					this.SendPropertyChanging();
					this._Комьютерные_сети = value;
					this.SendPropertyChanged("Комьютерные_сети");
					this.OnКомьютерные_сетиChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ПРСПО", DbType="Int")]
		public System.Nullable<int> ПРСПО
		{
			get
			{
				return this._ПРСПО;
			}
			set
			{
				if ((this._ПРСПО != value))
				{
					this.OnПРСПОChanging(value);
					this.SendPropertyChanging();
					this._ПРСПО = value;
					this.SendPropertyChanged("ПРСПО");
					this.OnПРСПОChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_АУДО", DbType="Int")]
		public System.Nullable<int> АУДО
		{
			get
			{
				return this._АУДО;
			}
			set
			{
				if ((this._АУДО != value))
				{
					this.OnАУДОChanging(value);
					this.SendPropertyChanging();
					this._АУДО = value;
					this.SendPropertyChanged("АУДО");
					this.OnАУДОChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ПССIП", DbType="Int")]
		public System.Nullable<int> ПССIП
		{
			get
			{
				return this._ПССIП;
			}
			set
			{
				if ((this._ПССIП != value))
				{
					this.OnПССIПChanging(value);
					this.SendPropertyChanging();
					this._ПССIП = value;
					this.SendPropertyChanged("ПССIП");
					this.OnПССIПChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ТиОПО", DbType="Int")]
		public System.Nullable<int> ТиОПО
		{
			get
			{
				return this._ТиОПО;
			}
			set
			{
				if ((this._ТиОПО != value))
				{
					this.OnТиОПОChanging(value);
					this.SendPropertyChanging();
					this._ТиОПО = value;
					this.SendPropertyChanged("ТиОПО");
					this.OnТиОПОChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ФКиЗ", DbType="Int")]
		public System.Nullable<int> ФКиЗ
		{
			get
			{
				return this._ФКиЗ;
			}
			set
			{
				if ((this._ФКиЗ != value))
				{
					this.OnФКиЗChanging(value);
					this.SendPropertyChanging();
					this._ФКиЗ = value;
					this.SendPropertyChanged("ФКиЗ");
					this.OnФКиЗChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Матмод", DbType="Int")]
		public System.Nullable<int> Матмод
		{
			get
			{
				return this._Матмод;
			}
			set
			{
				if ((this._Матмод != value))
				{
					this.OnМатмодChanging(value);
					this.SendPropertyChanging();
					this._Матмод = value;
					this.SendPropertyChanged("Матмод");
					this.OnМатмодChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ЗКИ", DbType="Int")]
		public System.Nullable<int> ЗКИ
		{
			get
			{
				return this._ЗКИ;
			}
			set
			{
				if ((this._ЗКИ != value))
				{
					this.OnЗКИChanging(value);
					this.SendPropertyChanging();
					this._ЗКИ = value;
					this.SendPropertyChanged("ЗКИ");
					this.OnЗКИChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ТРПО", DbType="Int")]
		public System.Nullable<int> ТРПО
		{
			get
			{
				return this._ТРПО;
			}
			set
			{
				if ((this._ТРПО != value))
				{
					this.OnТРПОChanging(value);
					this.SendPropertyChanging();
					this._ТРПО = value;
					this.SendPropertyChanged("ТРПО");
					this.OnТРПОChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ОП", DbType="Int")]
		public System.Nullable<int> ОП
		{
			get
			{
				return this._ОП;
			}
			set
			{
				if ((this._ОП != value))
				{
					this.OnОПChanging(value);
					this.SendPropertyChanging();
					this._ОП = value;
					this.SendPropertyChanged("ОП");
					this.OnОПChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_пользователя", DbType="Int NOT NULL")]
		public int ID_пользователя
		{
			get
			{
				return this._ID_пользователя;
			}
			set
			{
				if ((this._ID_пользователя != value))
				{
					this.OnID_пользователяChanging(value);
					this.SendPropertyChanging();
					this._ID_пользователя = value;
					this.SendPropertyChanged("ID_пользователя");
					this.OnID_пользователяChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
